/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'MY' at '11/29/16 11:26 AM' with Gradle 3.2.1
 *
 * @author MY, @date 11/29/16 11:26 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
